### ISSUE TITLE
Cannot find net.h

### ISSUE THREAD

**Issue by wildanazman** [Qengineering/Face-Recognition-Raspberry-Pi-64-bits#15]
![image](https://user-images.githubusercontent.com/85623687/165227610-24b2f276-4640-4058-9563-217ba2494940.png)
 Failed to compile because of this error. TMtCNN.h:8:10: fatal error: net.h: No such file or directory

**Comment by Qengineering** [comment]
@wildanazman,

Did you [install ncnn](https://qengineering.eu/install-ncnn-on-raspberry-pi-4.html) on your RPi beforehand? `net.h` is an ncnn header file.

![image](https://user-images.githubusercontent.com/44409029/165265747-5ecf7ead-db1a-4c8e-a2e3-0568246cfd5e.png)

**Comment by wildanazman** [comment]
![image](https://user-images.githubusercontent.com/85623687/165267245-71fbd1a4-70a6-409f-b0bf-2705ca513aeb.png)
Yes already install, but I think the program does not read the net.h file from the folder. Should I copy all the content in ncnn folder to src folder?

**Comment by Qengineering** [comment]
The other cause can be a missing search path in code::blocks.
![image](https://user-images.githubusercontent.com/44409029/165273629-e2c449c4-674c-440a-9147-7ab809839685.png)

**Comment by wildanazman** [comment]
![image](https://user-images.githubusercontent.com/85623687/165276829-63b2f4ff-6037-4d08-981c-261c37f9315d.png)
Got this error.

**Comment by Qengineering** [comment]
Those errors are all OpenCV related. Again, please check your OpenCV installation and/or the paths given in code::blocks
