### ISSUE TITLE
Not working with bullsye

### ISSUE THREAD

**Issue by rsingh2083** [Qengineering/Face-Recognition-Raspberry-Pi-64-bits#8]
Hi Sir,
There are two problems
1.] Your 64bit_Rpi4 image isnt updating due to  this error

`E: Repository 'http://raspbian.raspberrypi.org/raspbian buster InRelease' changed its 'Suite' value from 'testing' to 'stable'
`
2.] After updating to bullseye, the face recog code doesnt work (brief snippet of error)

```
bnll.cpp:(.text+0xf0): undefined reference to `__expf_finite'
/usr/bin/ld: bnll.cpp:(.text+0xf8): undefined reference to `__logf_finite'
/usr/bin/ld: bnll.cpp:(.text+0x13c): undefined reference to `__expf_finite'
/usr/bin/ld: bnll.cpp:(.text+0x144): undefined reference to `__logf_finite'
/usr/bin/ld: /usr/local/lib/ncnn/libncnn.a(convolution.cpp.o): in function `ncnn::Convolution::forward(ncnn::Mat const&, ncnn::Mat&, ncnn::Option const&) const [clone ._omp_fn.0]':
convolution.cpp:(.text+0x560): undefined reference to `__expf_finite'
/usr/bin/ld: convolution.cpp:(.text+0x57c): undefined reference to `__expf_finite'
/usr/bin/ld: convolution.cpp:(.text+0x5a4): undefined reference to `__logf_finite'
```

Can you please update the code to work with bullseye. And maybe fix the issue with Rpi4 image not getting updated/upgraded also

**Comment by Qengineering** [comment]
Dear @rsingh2083 
[1] The RPi-image is been updated and upgraded to the latest Debian 10 **Buster** release.
[2] Bullseye has a complete new and incompatible camera interface. You need to use [additional](https://github.com/Qengineering/LCCV) software to get everything working. Perhaps, in the near future, I will make a Bullseye image.

**Comment by rsingh2083** [comment]
Thanks Sir,
I had to install ubuntu 21.04 and build opencv and ncnn.Now its working.
Will try additional software on RPI and let you know
